const DATA_COMPONENT_TYPES = {
    FILE_UPLOAD: 'FILE_UPLOAD',
    FILE_DOWNLOAD: 'FILE_DOWNLOAD',
    FILTER_COLS: 'FILTER_COLS',
    FILTER_ROWS: 'FILTER_ROWS',
    JOIN: 'JOIN',
    UNION: 'UNION',
    SCRIPT: 'SCRIPT'
};

export default DATA_COMPONENT_TYPES;