const APP_ACTION_TYPES = {
    ADD_FILE_UPLOAD: 'ADD_FILE_UPLOAD',
    ADD_FILE_DOWNLOAD: 'ADD_FILE_DOWNLOAD',
    ADD_FILTER_COLS: 'ADD_FILTER_COLS',
    ADD_FILTER_ROWS: 'ADD_FILTER_ROWS',
    ADD_JOIN: 'ADD_JOIN',
    ADD_UNION: 'ADD_UNION',
    REMOVE_COMPONENET: 'REMOVE_COMPONENET'
};

export default APP_ACTION_TYPES;