const APP_ACTION_TYPES = {
    REMOVE_DATA_COMPONENT: 'REMOVE_DATA_COMPONENT',
    ADD_DATA_COMPONENT: 'ADD_DATA_COMPONENT',
    OPEN_CONNECT_COMPONENTS: 'OPEN_CONNECT_COMPONENTS',
    CLOSE_CONNECT_COMPONENTS: 'CLOSE_CONNECT_COMPONENTS',
    ADD_ARROW: 'ADD_ARROW',
    REMOVE_ARROW: 'REMOVE_ARROW',
    MODIFY_COMPONENT_DATA: 'MODIFY_COMPONENT_DATA',
    ADD_SOURCE_OUTPUT_REFS: 'ADD_SOURCE_OUTPUT_REFS',
    TOGGLE_IS_DRAGGING: 'TOGGLE_IS_DRAGGING',
    REMOVE_ALL: 'REMOVE_ALL'
};

export default APP_ACTION_TYPES;