const APP_ACTION_TYPES = {
    ADD_FILE_UPLOAD: 'ADD_FILE_UPLOAD',
    REMOVE_FILE_UPLOAD: 'REMOVE_FILE_UPLOAD',
    ADD_FILE_DOWNLOAD: 'ADD_FILE_DOWNLOAD',
    REMOVE_FILE_DOWNLOAD: 'REMOVE_FILE_DOWNLOAD',
    ADD_FILTER_COLS: 'ADD_FILTER_COLS',
    REMOVE_FILTER_COLS: 'REMOVE_FILTER_COLS',
    ADD_FILTER_ROWS: 'ADD_FILTER_ROWS',
    REMOVE_FILTER_ROWS: 'REMOVE_FILTER_ROWS',
    ADD_JOIN: 'ADD_JOIN',
    REMOVE_JOIN: 'REMOVE_JOIN',
    ADD_UNION: 'ADD_UNION',
    REMOVE_UNION: 'REMOVE_UNION'
};

export default APP_ACTION_TYPES;